name: "🎉 Release new version"

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Release type
        options:
          - " -- --patch"
          - " -- --minor"
  push:
    branches:
      - master
    paths:
      - "packages/daisyui/**"

jobs:
  build-publish:
    name: 🔨 Build + 🚀 Publish
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      daisyuiversion: ${{ steps.package-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Build package
        run: bun run build

      - name: Run release command
        if: github.repository == 'saadeghi/daisyui'
        run: |
          git config --local user.email "pouya.saadeghi@gmail.com"
          git config --local user.name "Pouya Saadeghi"
          bun run release${{ inputs.release-type }}

      - name: Read package version from package.json
        id: package-version
        run: |
          version=$(grep -o '"version": *"[^"]*"' packages/daisyui/package.json | cut -d'"' -f4)
          echo version=$version >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to NPM
        if: github.repository == 'saadeghi/daisyui'
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-docs:
    name: 📘 Docs
    needs: build-publish
    uses: ./.github/workflows/deploy-docs.yml
    secrets: inherit
    with:
      daisyuiversion: ${{ needs.build-publish.outputs.daisyuiversion }}

  run-tests:
    name: 🧪 Tests
    needs: build-publish
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      filter: ""

  write-release-notes:
    name: 📝 Release notes
    if: github.repository == 'saadeghi/daisyui'
    needs: build-publish
    uses: ./.github/workflows/write-release-notes.yml
    secrets: inherit
    with:
      daisyuiversion: ${{ needs.build-publish.outputs.daisyuiversion }}
